package com.mybatis.demo.mapper;

import com.mybatis.demo.entity.Buycar;

import java.util.List;

public interface BuycarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buycar
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buycar
     *
     * @mbg.generated
     */
    int insert(Buycar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buycar
     *
     * @mbg.generated
     */
    Buycar selectByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buycar
     *
     * @mbg.generated
     */
    List<Buycar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buycar
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Buycar record);
}