package com.mybatis.demo.mapper;

import com.mybatis.demo.entity.Charge;

import java.util.List;

public interface ChargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer chargeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge
     *
     * @mbg.generated
     */
    int insert(Charge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge
     *
     * @mbg.generated
     */
    Charge selectByPrimaryKey(Integer chargeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge
     *
     * @mbg.generated
     */
    List<Charge> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Charge record);
}