package com.mybatis.demo.mapper;

import com.mybatis.demo.entity.Itemcharge;

import java.util.List;

public interface ItemchargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcharge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer itemchargeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcharge
     *
     * @mbg.generated
     */
    int insert(Itemcharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcharge
     *
     * @mbg.generated
     */
    Itemcharge selectByPrimaryKey(Integer itemchargeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcharge
     *
     * @mbg.generated
     */
    List<Itemcharge> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcharge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Itemcharge record);
}