package com.mybatis.demo.mapper;

import com.mybatis.demo.entity.Storeinfo;

import java.util.List;

public interface StoreinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storeinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer storeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storeinfo
     *
     * @mbg.generated
     */
    int insert(Storeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storeinfo
     *
     * @mbg.generated
     */
    Storeinfo selectByPrimaryKey(Integer storeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storeinfo
     *
     * @mbg.generated
     */
    List<Storeinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storeinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Storeinfo record);
}