package com.mybatis.demo.mapper;

import com.mybatis.demo.entity.Userlog;

import java.util.List;

public interface UserlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated
     */
    int insert(Userlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated
     */
    Userlog selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated
     */
    List<Userlog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userlog record);
}