package com.mybatis.demo.entity;

public class Buycar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buycar.itemid
     *
     * @mbg.generated
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buycar.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buycar.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buycar.itemcount
     *
     * @mbg.generated
     */
    private Integer itemcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buycar.totalprice
     *
     * @mbg.generated
     */
    private Integer totalprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buycar.itemid
     *
     * @return the value of buycar.itemid
     * @mbg.generated
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buycar.itemid
     *
     * @param itemid the value for buycar.itemid
     * @mbg.generated
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buycar.userid
     *
     * @return the value of buycar.userid
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buycar.userid
     *
     * @param userid the value for buycar.userid
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buycar.price
     *
     * @return the value of buycar.price
     * @mbg.generated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buycar.price
     *
     * @param price the value for buycar.price
     * @mbg.generated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buycar.itemcount
     *
     * @return the value of buycar.itemcount
     * @mbg.generated
     */
    public Integer getItemcount() {
        return itemcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buycar.itemcount
     *
     * @param itemcount the value for buycar.itemcount
     * @mbg.generated
     */
    public void setItemcount(Integer itemcount) {
        this.itemcount = itemcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buycar.totalprice
     *
     * @return the value of buycar.totalprice
     * @mbg.generated
     */
    public Integer getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buycar.totalprice
     *
     * @param totalprice the value for buycar.totalprice
     * @mbg.generated
     */
    public void setTotalprice(Integer totalprice) {
        this.totalprice = totalprice;
    }
}