package com.mybatis.demo.entity;

import java.util.Date;

public class Charge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.chargeid
     *
     * @mbg.generated
     */
    private Integer chargeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.storeid
     *
     * @mbg.generated
     */
    private Integer storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.itemchargeid
     *
     * @mbg.generated
     */
    private Integer itemchargeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.totalprice
     *
     * @mbg.generated
     */
    private Integer totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.consumetime
     *
     * @mbg.generated
     */
    private Date consumetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.chargeid
     *
     * @return the value of charge.chargeid
     * @mbg.generated
     */
    public Integer getChargeid() {
        return chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.chargeid
     *
     * @param chargeid the value for charge.chargeid
     * @mbg.generated
     */
    public void setChargeid(Integer chargeid) {
        this.chargeid = chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.userid
     *
     * @return the value of charge.userid
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.userid
     *
     * @param userid the value for charge.userid
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.storeid
     *
     * @return the value of charge.storeid
     * @mbg.generated
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.storeid
     *
     * @param storeid the value for charge.storeid
     * @mbg.generated
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.itemchargeid
     *
     * @return the value of charge.itemchargeid
     * @mbg.generated
     */
    public Integer getItemchargeid() {
        return itemchargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.itemchargeid
     *
     * @param itemchargeid the value for charge.itemchargeid
     * @mbg.generated
     */
    public void setItemchargeid(Integer itemchargeid) {
        this.itemchargeid = itemchargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.totalprice
     *
     * @return the value of charge.totalprice
     * @mbg.generated
     */
    public Integer getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.totalprice
     *
     * @param totalprice the value for charge.totalprice
     * @mbg.generated
     */
    public void setTotalprice(Integer totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.consumetime
     *
     * @return the value of charge.consumetime
     * @mbg.generated
     */
    public Date getConsumetime() {
        return consumetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.consumetime
     *
     * @param consumetime the value for charge.consumetime
     * @mbg.generated
     */
    public void setConsumetime(Date consumetime) {
        this.consumetime = consumetime;
    }
}