package com.mybatis.demo.entity;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Class.classId
     *
     * @mbg.generated
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Class.className
     *
     * @mbg.generated
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Class.departmentId
     *
     * @mbg.generated
     */
    private Integer departmentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Class.classId
     *
     * @return the value of Class.classId
     * @mbg.generated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Class.classId
     *
     * @param classid the value for Class.classId
     * @mbg.generated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Class.className
     *
     * @return the value of Class.className
     * @mbg.generated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Class.className
     *
     * @param classname the value for Class.className
     * @mbg.generated
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Class.departmentId
     *
     * @return the value of Class.departmentId
     * @mbg.generated
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Class.departmentId
     *
     * @param departmentid the value for Class.departmentId
     * @mbg.generated
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }
}