package com.mybatis.demo.entity;

import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.courseId
     *
     * @mbg.generated
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.courseName
     *
     * @mbg.generated
     */
    private String coursename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.startTime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.courseImg
     *
     * @mbg.generated
     */
    private String courseimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.endTime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.courseId
     *
     * @return the value of Course.courseId
     * @mbg.generated
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.courseId
     *
     * @param courseid the value for Course.courseId
     * @mbg.generated
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.courseName
     *
     * @return the value of Course.courseName
     * @mbg.generated
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.courseName
     *
     * @param coursename the value for Course.courseName
     * @mbg.generated
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.content
     *
     * @return the value of Course.content
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.content
     *
     * @param content the value for Course.content
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.startTime
     *
     * @return the value of Course.startTime
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.startTime
     *
     * @param starttime the value for Course.startTime
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.courseImg
     *
     * @return the value of Course.courseImg
     * @mbg.generated
     */
    public String getCourseimg() {
        return courseimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.courseImg
     *
     * @param courseimg the value for Course.courseImg
     * @mbg.generated
     */
    public void setCourseimg(String courseimg) {
        this.courseimg = courseimg == null ? null : courseimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.endTime
     *
     * @return the value of Course.endTime
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.endTime
     *
     * @param endtime the value for Course.endTime
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}