package com.mybatis.demo.entity;

public class Itemcharge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemcharge.itemchargeid
     *
     * @mbg.generated
     */
    private Integer itemchargeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemcharge.itemid
     *
     * @mbg.generated
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemcharge.itemcount
     *
     * @mbg.generated
     */
    private Integer itemcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemcharge.itemchargeid
     *
     * @return the value of itemcharge.itemchargeid
     * @mbg.generated
     */
    public Integer getItemchargeid() {
        return itemchargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemcharge.itemchargeid
     *
     * @param itemchargeid the value for itemcharge.itemchargeid
     * @mbg.generated
     */
    public void setItemchargeid(Integer itemchargeid) {
        this.itemchargeid = itemchargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemcharge.itemid
     *
     * @return the value of itemcharge.itemid
     * @mbg.generated
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemcharge.itemid
     *
     * @param itemid the value for itemcharge.itemid
     * @mbg.generated
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemcharge.itemcount
     *
     * @return the value of itemcharge.itemcount
     * @mbg.generated
     */
    public Integer getItemcount() {
        return itemcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemcharge.itemcount
     *
     * @param itemcount the value for itemcharge.itemcount
     * @mbg.generated
     */
    public void setItemcount(Integer itemcount) {
        this.itemcount = itemcount;
    }
}