package com.mybatis.demo.entity;

public class Learnclass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learnClass.learnClassId
     *
     * @mbg.generated
     */
    private Integer learnclassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learnClass.teachClassId
     *
     * @mbg.generated
     */
    private Integer teachclassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learnClass.studentId
     *
     * @mbg.generated
     */
    private Integer studentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learnClass.learnClassId
     *
     * @return the value of learnClass.learnClassId
     * @mbg.generated
     */
    public Integer getLearnclassid() {
        return learnclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learnClass.learnClassId
     *
     * @param learnclassid the value for learnClass.learnClassId
     * @mbg.generated
     */
    public void setLearnclassid(Integer learnclassid) {
        this.learnclassid = learnclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learnClass.teachClassId
     *
     * @return the value of learnClass.teachClassId
     * @mbg.generated
     */
    public Integer getTeachclassid() {
        return teachclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learnClass.teachClassId
     *
     * @param teachclassid the value for learnClass.teachClassId
     * @mbg.generated
     */
    public void setTeachclassid(Integer teachclassid) {
        this.teachclassid = teachclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learnClass.studentId
     *
     * @return the value of learnClass.studentId
     * @mbg.generated
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learnClass.studentId
     *
     * @param studentid the value for learnClass.studentId
     * @mbg.generated
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }
}