package com.mybatis.demo.entity;

import java.util.Date;

public class Maintitle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainTitle.mainTitleId
     *
     * @mbg.generated
     */
    private Integer maintitleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainTitle.teachClassId
     *
     * @mbg.generated
     */
    private Integer teachclassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainTitle.teacherId
     *
     * @mbg.generated
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainTitle.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainTitle.body
     *
     * @mbg.generated
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainTitle.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainTitle.mainTitleId
     *
     * @return the value of mainTitle.mainTitleId
     * @mbg.generated
     */
    public Integer getMaintitleid() {
        return maintitleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainTitle.mainTitleId
     *
     * @param maintitleid the value for mainTitle.mainTitleId
     * @mbg.generated
     */
    public void setMaintitleid(Integer maintitleid) {
        this.maintitleid = maintitleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainTitle.teachClassId
     *
     * @return the value of mainTitle.teachClassId
     * @mbg.generated
     */
    public Integer getTeachclassid() {
        return teachclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainTitle.teachClassId
     *
     * @param teachclassid the value for mainTitle.teachClassId
     * @mbg.generated
     */
    public void setTeachclassid(Integer teachclassid) {
        this.teachclassid = teachclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainTitle.teacherId
     *
     * @return the value of mainTitle.teacherId
     * @mbg.generated
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainTitle.teacherId
     *
     * @param teacherid the value for mainTitle.teacherId
     * @mbg.generated
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainTitle.title
     *
     * @return the value of mainTitle.title
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainTitle.title
     *
     * @param title the value for mainTitle.title
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainTitle.body
     *
     * @return the value of mainTitle.body
     * @mbg.generated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainTitle.body
     *
     * @param body the value for mainTitle.body
     * @mbg.generated
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainTitle.createTime
     *
     * @return the value of mainTitle.createTime
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainTitle.createTime
     *
     * @param createtime the value for mainTitle.createTime
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}