package com.mybatis.demo.entity;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.itemid
     *
     * @mbg.generated
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.storeid
     *
     * @mbg.generated
     */
    private Integer storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.itempng
     *
     * @mbg.generated
     */
    private String itempng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.itemprice
     *
     * @mbg.generated
     */
    private Integer itemprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.itemid
     *
     * @return the value of menu.itemid
     * @mbg.generated
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.itemid
     *
     * @param itemid the value for menu.itemid
     * @mbg.generated
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.storeid
     *
     * @return the value of menu.storeid
     * @mbg.generated
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.storeid
     *
     * @param storeid the value for menu.storeid
     * @mbg.generated
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.itempng
     *
     * @return the value of menu.itempng
     * @mbg.generated
     */
    public String getItempng() {
        return itempng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.itempng
     *
     * @param itempng the value for menu.itempng
     * @mbg.generated
     */
    public void setItempng(String itempng) {
        this.itempng = itempng == null ? null : itempng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.itemprice
     *
     * @return the value of menu.itemprice
     * @mbg.generated
     */
    public Integer getItemprice() {
        return itemprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.itemprice
     *
     * @param itemprice the value for menu.itemprice
     * @mbg.generated
     */
    public void setItemprice(Integer itemprice) {
        this.itemprice = itemprice;
    }
}