package com.mybatis.demo.entity;

public class Storeinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeinfo.storeid
     *
     * @mbg.generated
     */
    private Integer storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeinfo.logid
     *
     * @mbg.generated
     */
    private Integer logid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeinfo.storepng
     *
     * @mbg.generated
     */
    private String storepng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeinfo.storename
     *
     * @mbg.generated
     */
    private String storename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeinfo.info
     *
     * @mbg.generated
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeinfo.storeid
     *
     * @return the value of storeinfo.storeid
     * @mbg.generated
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeinfo.storeid
     *
     * @param storeid the value for storeinfo.storeid
     * @mbg.generated
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeinfo.logid
     *
     * @return the value of storeinfo.logid
     * @mbg.generated
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeinfo.logid
     *
     * @param logid the value for storeinfo.logid
     * @mbg.generated
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeinfo.storepng
     *
     * @return the value of storeinfo.storepng
     * @mbg.generated
     */
    public String getStorepng() {
        return storepng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeinfo.storepng
     *
     * @param storepng the value for storeinfo.storepng
     * @mbg.generated
     */
    public void setStorepng(String storepng) {
        this.storepng = storepng == null ? null : storepng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeinfo.storename
     *
     * @return the value of storeinfo.storename
     * @mbg.generated
     */
    public String getStorename() {
        return storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeinfo.storename
     *
     * @param storename the value for storeinfo.storename
     * @mbg.generated
     */
    public void setStorename(String storename) {
        this.storename = storename == null ? null : storename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeinfo.info
     *
     * @return the value of storeinfo.info
     * @mbg.generated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeinfo.info
     *
     * @param info the value for storeinfo.info
     * @mbg.generated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}