package com.mybatis.demo.entity;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacherId
     *
     * @mbg.generated
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.userId
     *
     * @mbg.generated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.departmentid
     *
     * @mbg.generated
     */
    private Integer departmentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacherId
     *
     * @return the value of teacher.teacherId
     * @mbg.generated
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacherId
     *
     * @param teacherid the value for teacher.teacherId
     * @mbg.generated
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.userId
     *
     * @return the value of teacher.userId
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.userId
     *
     * @param userid the value for teacher.userId
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.departmentid
     *
     * @return the value of teacher.departmentid
     * @mbg.generated
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.departmentid
     *
     * @param departmentid the value for teacher.departmentid
     * @mbg.generated
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }
}