package com.mybatis.demo.entity;

public class Teachclass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachClass.teachClassId
     *
     * @mbg.generated
     */
    private Integer teachclassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachClass.teacherId
     *
     * @mbg.generated
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachClass.courseId
     *
     * @mbg.generated
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachClass.classId
     *
     * @mbg.generated
     */
    private Integer classid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachClass.teachClassId
     *
     * @return the value of teachClass.teachClassId
     * @mbg.generated
     */
    public Integer getTeachclassid() {
        return teachclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachClass.teachClassId
     *
     * @param teachclassid the value for teachClass.teachClassId
     * @mbg.generated
     */
    public void setTeachclassid(Integer teachclassid) {
        this.teachclassid = teachclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachClass.teacherId
     *
     * @return the value of teachClass.teacherId
     * @mbg.generated
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachClass.teacherId
     *
     * @param teacherid the value for teachClass.teacherId
     * @mbg.generated
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachClass.courseId
     *
     * @return the value of teachClass.courseId
     * @mbg.generated
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachClass.courseId
     *
     * @param courseid the value for teachClass.courseId
     * @mbg.generated
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachClass.classId
     *
     * @return the value of teachClass.classId
     * @mbg.generated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachClass.classId
     *
     * @param classid the value for teachClass.classId
     * @mbg.generated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }
}