package com.mybatis.demo.entity;

import java.util.Date;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topicId
     *
     * @mbg.generated
     */
    private Integer topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.mainTitleId
     *
     * @mbg.generated
     */
    private Integer maintitleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.body
     *
     * @mbg.generated
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topicId
     *
     * @return the value of topic.topicId
     * @mbg.generated
     */
    public Integer getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topicId
     *
     * @param topicid the value for topic.topicId
     * @mbg.generated
     */
    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.mainTitleId
     *
     * @return the value of topic.mainTitleId
     * @mbg.generated
     */
    public Integer getMaintitleid() {
        return maintitleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.mainTitleId
     *
     * @param maintitleid the value for topic.mainTitleId
     * @mbg.generated
     */
    public void setMaintitleid(Integer maintitleid) {
        this.maintitleid = maintitleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.userid
     *
     * @return the value of topic.userid
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.userid
     *
     * @param userid the value for topic.userid
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.body
     *
     * @return the value of topic.body
     * @mbg.generated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.body
     *
     * @param body the value for topic.body
     * @mbg.generated
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.createTime
     *
     * @return the value of topic.createTime
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.createTime
     *
     * @param createtime the value for topic.createTime
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}