package com.mybatis.demo.entity;

public class Userlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.logtype
     *
     * @mbg.generated
     */
    private Integer logtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.userid
     *
     * @return the value of userlog.userid
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.userid
     *
     * @param userid the value for userlog.userid
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.username
     *
     * @return the value of userlog.username
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.username
     *
     * @param username the value for userlog.username
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.password
     *
     * @return the value of userlog.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.password
     *
     * @param password the value for userlog.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.logtype
     *
     * @return the value of userlog.logtype
     * @mbg.generated
     */
    public Integer getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.logtype
     *
     * @param logtype the value for userlog.logtype
     * @mbg.generated
     */
    public void setLogtype(Integer logtype) {
        this.logtype = logtype;
    }
}